name = "chat-proxy"
main = "chat-proxy.js"
compatibility_date = "2024-01-01"

# 环境变量（需要在Cloudflare Dashboard中设置）
[env.production.vars]
# CHAT_API_KEY = "your-api-key-here"  # 在Dashboard中设置，不要写在这里
# ALLOWED_ORIGINS = "https://zhu-jl18.github.io"  # 在Dashboard中设置
## [removed] TTS-related envs have been deprecated

# KV存储（用于速率限制，可选）
[[kv_namespaces]]
binding = "CHAT_RATE_LIMIT"
id = "your-kv-namespace-id"  # 创建KV namespace后填入ID
preview_id = "your-preview-kv-namespace-id"  # 预览环境的KV ID

## [removed] TTS R2 bucket binding (unused)
